import type { Metadata } from "next";
// import { Roboto } from "next/font/google";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Navigation from "@/components/navigation";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,

}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body className="min-h-full flex flex-col" >
                <div className=" px-4 container max-w-360 mx-auto">
                    <Header />
                    <div className="flex gap-7.5 px-33">
                        <Navigation />
                        {children}
                    </div>
                    <Footer />
                </div>
            </body>
        </html>
    )
}