import type { Metadata } from "next";
// import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
})

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Breadcrumbs from '@/components/Breadcrumbs';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${roboto.className} h-full antialiased`}
      suppressHydrationWarning={true}
    >
      <body className="min-h-full flex flex-col" >
        <div className=" px-4 container max-w-360 mx-auto">
          <Header />
          <Breadcrumbs />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
