import type { Metadata } from "next";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
// import Breadcrumbs from '@/components/Breadcrumbs';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className=" px-4 container max-w-360 mx-auto">
          <Header />
          {/* <Breadcrumbs /> */}
          {children}
          <Footer />
        </div>
  );
}
